# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/agent_bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/agent_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/agent_bridge.proto\x12\x14temporal_hack.bridge\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x10SubscribeRequest\x12\x0f\n\x07streams\x18\x01 \x03(\t\"\xe3\x01\n\nTopicEvent\x12\x0e\n\x06stream\x18\x01 \x01(\t\x12/\n\x0b\x63\x61ptured_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x16\n\x0epayload_schema\x18\x04 \x01(\t\x12<\n\x06labels\x18\x05 \x03(\x0b\x32,.temporal_hack.bridge.TopicEvent.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x0f\n\rHealthRequest\"\xa4\x01\n\x0eHealthResponse\x12\x39\n\x05state\x18\x01 \x01(\x0e\x32*.temporal_hack.bridge.HealthResponse.State\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63tive_streams\x18\x03 \x03(\t\"/\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07HEALTHY\x10\x01\x12\x0c\n\x08\x44\x45GRADED\x10\x02\x32\xb6\x01\n\x06\x42ridge\x12W\n\tSubscribe\x12&.temporal_hack.bridge.SubscribeRequest\x1a .temporal_hack.bridge.TopicEvent0\x01\x12S\n\x06Health\x12#.temporal_hack.bridge.HealthRequest\x1a$.temporal_hack.bridge.HealthResponseB;Z9github.com/example/temporal-hack/agent/internal/bridge/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.agent_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/example/temporal-hack/agent/internal/bridge/pb'
  _globals['_TOPICEVENT_LABELSENTRY']._loaded_options = None
  _globals['_TOPICEVENT_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_SUBSCRIBEREQUEST']._serialized_start=83
  _globals['_SUBSCRIBEREQUEST']._serialized_end=118
  _globals['_TOPICEVENT']._serialized_start=121
  _globals['_TOPICEVENT']._serialized_end=348
  _globals['_TOPICEVENT_LABELSENTRY']._serialized_start=303
  _globals['_TOPICEVENT_LABELSENTRY']._serialized_end=348
  _globals['_HEALTHREQUEST']._serialized_start=350
  _globals['_HEALTHREQUEST']._serialized_end=365
  _globals['_HEALTHRESPONSE']._serialized_start=368
  _globals['_HEALTHRESPONSE']._serialized_end=532
  _globals['_HEALTHRESPONSE_STATE']._serialized_start=485
  _globals['_HEALTHRESPONSE_STATE']._serialized_end=532
  _globals['_BRIDGE']._serialized_start=535
  _globals['_BRIDGE']._serialized_end=717
# @@protoc_insertion_point(module_scope)
