# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_bridge_pb2 as proto_dot_agent__bridge__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/agent_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BridgeStub(object):
    """gRPC contract between the Go robot agent and the ROS 2 bridge node.
    Transport is gRPC over a Unix domain socket on the robot. Agent is
    the client; bridge is the server.

    Design principle (D-06): the agent must NOT import ROS. All DDS
    interaction is the bridge's responsibility. The agent treats the
    bridge as an opaque source of structured topic events.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/temporal_hack.bridge.Bridge/Subscribe',
                request_serializer=proto_dot_agent__bridge__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=proto_dot_agent__bridge__pb2.TopicEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/temporal_hack.bridge.Bridge/Health',
                request_serializer=proto_dot_agent__bridge__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_agent__bridge__pb2.HealthResponse.FromString,
                _registered_method=True)


class BridgeServicer(object):
    """gRPC contract between the Go robot agent and the ROS 2 bridge node.
    Transport is gRPC over a Unix domain socket on the robot. Agent is
    the client; bridge is the server.

    Design principle (D-06): the agent must NOT import ROS. All DDS
    interaction is the bridge's responsibility. The agent treats the
    bridge as an opaque source of structured topic events.

    """

    def Subscribe(self, request, context):
        """Stream selected ROS 2 topic events to the agent. Bridge node
        owns the topic→stream mapping; agent picks streams by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Liveness probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=proto_dot_agent__bridge__pb2.SubscribeRequest.FromString,
                    response_serializer=proto_dot_agent__bridge__pb2.TopicEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=proto_dot_agent__bridge__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_agent__bridge__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temporal_hack.bridge.Bridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('temporal_hack.bridge.Bridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bridge(object):
    """gRPC contract between the Go robot agent and the ROS 2 bridge node.
    Transport is gRPC over a Unix domain socket on the robot. Agent is
    the client; bridge is the server.

    Design principle (D-06): the agent must NOT import ROS. All DDS
    interaction is the bridge's responsibility. The agent treats the
    bridge as an opaque source of structured topic events.

    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/temporal_hack.bridge.Bridge/Subscribe',
            proto_dot_agent__bridge__pb2.SubscribeRequest.SerializeToString,
            proto_dot_agent__bridge__pb2.TopicEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temporal_hack.bridge.Bridge/Health',
            proto_dot_agent__bridge__pb2.HealthRequest.SerializeToString,
            proto_dot_agent__bridge__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
