# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ota.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/ota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/ota.proto\x12\x11temporal_hack.ota\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n\nOTACommand\x12\x12\n\nrollout_id\x18\x01 \x01(\t\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x11\n\timage_ref\x18\x03 \x01(\t\x12\x14\n\x0cimage_digest\x18\x04 \x01(\t\x12\x19\n\x11smoke_timeout_sec\x18\x05 \x01(\r\x12\x15\n\rsmoke_command\x18\x06 \x01(\t\x12\r\n\x05\x66orce\x18\x07 \x01(\x08\"\xc4\x01\n\x06OTAAck\x12\x12\n\nrollout_id\x18\x01 \x01(\t\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\'\n\x05phase\x18\x03 \x01(\x0e\x32\x18.temporal_hack.ota.Phase\x12&\n\x02\x61t\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cimage_digest\x18\x05 \x01(\t\x12\x1d\n\x15previous_image_digest\x18\x06 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x07 \x01(\t*\x8f\x01\n\x05Phase\x12\x11\n\rPHASE_UNKNOWN\x10\x00\x12\x12\n\x0ePHASE_RECEIVED\x10\x01\x12\x10\n\x0cPHASE_PULLED\x10\x02\x12\x11\n\rPHASE_SWAPPED\x10\x03\x12\x11\n\rPHASE_HEALTHY\x10\x04\x12\x10\n\x0cPHASE_FAILED\x10\x05\x12\x15\n\x11PHASE_ROLLED_BACK\x10\x06\x42\x38Z6github.com/example/temporal-hack/cloud/internal/ota/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/example/temporal-hack/cloud/internal/ota/pb'
  _globals['_PHASE']._serialized_start=430
  _globals['_PHASE']._serialized_end=573
  _globals['_OTACOMMAND']._serialized_start=72
  _globals['_OTACOMMAND']._serialized_end=228
  _globals['_OTAACK']._serialized_start=231
  _globals['_OTAACK']._serialized_end=427
# @@protoc_insertion_point(module_scope)
