# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/telemetry.proto\x12\x17temporal_hack.telemetry\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n\x06Sample\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x0e\n\x06stream\x18\x02 \x01(\t\x12/\n\x0b\x63\x61ptured_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nemitted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08sequence\x18\x05 \x01(\x04\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x12\x16\n\x0epayload_schema\x18\x07 \x01(\t\x12;\n\x06labels\x18\x08 \x03(\x0b\x32+.temporal_hack.telemetry.Sample.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa8\x01\n\tHeartbeat\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12.\n\nemitted_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\ragent_version\x18\x03 \x01(\t\x12\x18\n\x10ota_image_digest\x18\x04 \x01(\t\x12\x18\n\x10\x62uffered_samples\x18\x05 \x01(\x04\x12\x0e\n\x06status\x18\x06 \x01(\tB>Z<github.com/example/temporal-hack/cloud/internal/telemetry/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/example/temporal-hack/cloud/internal/telemetry/pb'
  _globals['_SAMPLE_LABELSENTRY']._loaded_options = None
  _globals['_SAMPLE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLE']._serialized_start=84
  _globals['_SAMPLE']._serialized_end=390
  _globals['_SAMPLE_LABELSENTRY']._serialized_start=345
  _globals['_SAMPLE_LABELSENTRY']._serialized_end=390
  _globals['_HEARTBEAT']._serialized_start=393
  _globals['_HEARTBEAT']._serialized_end=561
# @@protoc_insertion_point(module_scope)
